-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "Hawkeye"
local Event = game:GetService("ReplicatedStorage").Core.Functions.GiveCharacter
Event:InvokeServer(A_1)
wait(5)
game:GetService("Players").MisterSpectatorous.PlayerGui.CharacterSelectionUI.SkinCustomization:Destroy()

--list
--Quicksilver
--Spider-Man
--Hawkeye