-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
while wait() do
local A_1 = game:GetService("Workspace").NumbersAreFaked.Humanoid
local A_2 = -1000000
local A_3 = false
local Event = game:GetService("ReplicatedStorage").GunRemotes.TakeDamage
Event:FireServer(A_1, A_2, A_3)
end