-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = 
{
	["Missions"] = 
{
}, 
	["PlacesUnlocked"] = 
{
	[1] = 5326145070
}, 
	["Data"] = 
{
	["Stat_Points"] = 9931, 
	["Bounty"] = 10000, 
	["Side"] = "Pirate", 
	["Beli"] = 99999999089, 
	["Mastery"] = 
{
	["Demon Art"] = 
{
	[1] = 100, 
	[2] = 100
}, 
	["Defense"] = 
{
	[1] = 100, 
	[2] = 100
}, 
	["Strength"] = 
{
	[1] = 100, 
	[2] = 100
}, 
	["Sword"] = 
{
	[1] = 100, 
	[2] = 100
}, 
	["Breathing Technique"] = 
{
	[1] = 100, 
	[2] = 100
}, 
	["Agility"] = 
{
	[1] = 100, 
	[2] = 100
}
}, 
	["Exp"] = 
{
	[1] = 0, 
	[2] = 9000
}
}, 
	["Themes"] = true, 
	["DataById"] = 
{
}, 
	["Race"] = 4, 
	["ThemesVolume"] = 
{
	[1] = 3, 
	[2] = 10
}, 
	["Keys"] = 
{
	["Interact"] = 
{
	["Key"] = "E", 
	["Toggle"] = false
}, 
	["Move5"] = 
{
	["Key"] = "B", 
	["Toggle"] = false
}, 
	["Move2"] = 
{
	["Key"] = "X", 
	["Toggle"] = false
}, 
	["Move6"] = 
{
	["Key"] = "N", 
	["Toggle"] = false
}, 
	["Menu"] = 
{
	["Key"] = "M", 
	["Toggle"] = false
}, 
	["Move1"] = 
{
	["Key"] = "Z", 
	["Toggle"] = false
}, 
	["Run"] = 
{
	["Key"] = "LeftShift", 
	["Toggle"] = false
}, 
	["Move4"] = 
{
	["Key"] = "V", 
	["Toggle"] = false
}, 
	["Move3"] = 
{
	["Key"] = "C", 
	["Toggle"] = false
}
}, 
	["BreathingProgression"] = 
{
	[1] = 60, 
	[2] = 60
}, 
	["Power"] = "Thunder Breathing", 
	["KeyBinds"] = 
{
	["Move2"] = "Heat Lightning", 
	["Move6"] = "Thunder Swarm", 
	["Move1"] = "Thunderclap and Flash", 
	["Move4"] = "Rice Spirit", 
	["Move5"] = "Distance Thunder", 
	["Move3"] = "Thunderclap and Flash Sixfold"
}, 
	["EffectsVolume"] = 
{
	[1] = 5, 
	[2] = 10
}, 
	["Customization"] = 
{
	["FishManColor"] = 1, 
	["Face"] = 1, 
	["RaceSpins"] = 99999, 
	["AccessoryColor2"] = 
{
	["R"] = 0, 
	["G"] = 0, 
	["B"] = 0
}, 
	["FishPart"] = 1, 
	["Hair2"] = 0, 
	["MarineCloths"] = true, 
	["MinkSecondary"] = 0, 
	["MarineHat"] = true, 
	["AccessoryEnabled"] = false, 
	["HairColor"] = 
{
	["R"] = 0, 
	["G"] = 0, 
	["B"] = 0
}, 
	["HairColor2"] = 
{
	["R"] = 0, 
	["G"] = 0, 
	["B"] = 0
}, 
	["MinkPart"] = 1, 
	["BeardColor"] = 
{
	["R"] = 0, 
	["G"] = 0, 
	["B"] = 0
}, 
	["AccessoryColor"] = 
{
	["R"] = 0, 
	["G"] = 0, 
	["B"] = 0
}, 
	["FishSecondary"] = 0, 
	["Beard"] = 0, 
	["Hair"] = 0
}, 
	["playerspawn"] = "None", 
	["Quests"] = 
{
}, 
	["RewardSystem"] = 
{
	["RewardDay"] = 1625103249.491, 
	["GotReward"] = 0, 
	["LastRewardTick"] = 1625103249.491
}, 
	["Inventory"] = 
{
	["Equiped"] = 
{
	["Tools"] = 
{
	[1] = 2, 
	[2] = 1
}, 
	["Weapons"] = 
{
	["RightArm"] = "", 
	["LeftArm"] = "", 
	["Head"] = ""
}, 
	["Clothes"] = 
{
	["Pants"] = 7, 
	["Hat"] = 6, 
	["Shirt"] = 4, 
	["Hat2"] = 5
}
}, 
	["Items"] = 
{
	[1] = 
{
	["Type"] = "Tool", 
	["Name"] = "Combat", 
	["Id"] = 1, 
	["Rarity"] = "Common", 
	["Stats"] = 
{
	["Defense"] = 
{
	[1] = 100, 
	[2] = 100
}
}
}, 
	[2] = 
{
	["Type"] = "Tool", 
	["Name"] = "Black Katana", 
	["Id"] = 2, 
	["Stats"] = 
{
	["Strength"] = 
{
	[1] = 10, 
	[2] = 100
}, 
	["Defense"] = 
{
	[1] = 15, 
	[2] = 100
}
}, 
	["Health"] = 
{
	[1] = 0, 
	[2] = 10
}, 
	["Rarity"] = "Legendary"
}, 
	[3] = 
{
	["Type"] = "Shirt", 
	["Rarity"] = "Common", 
	["Id"] = 5574104524, 
	["RealId"] = 4, 
	["Name"] = "Top Grey Winter Coat"
}, 
	[4] = 
{
	["Type"] = "Shirt", 
	["Rarity"] = "Common", 
	["Id"] = 5574104524, 
	["RealId"] = 4, 
	["Name"] = "Top Grey Winter Coat"
}, 
	[5] = 
{
	["Type"] = "Hat", 
	["Name"] = "Spiky Cape", 
	["Numb"] = 7, 
	["RealId"] = 5, 
	["Rarity"] = "Common"
}, 
	[6] = 
{
	["Type"] = "Hat", 
	["Name"] = "Yare Yare", 
	["Numb"] = 9, 
	["RealId"] = 6, 
	["Rarity"] = "Common"
}, 
	[7] = 
{
	["Type"] = "Pants", 
	["Rarity"] = "Common", 
	["Id"] = 5574108945, 
	["RealId"] = 7, 
	["Name"] = "Bottom Grey Winter Coat"
}
}
}, 
	["Ships"] = 
{
}, 
	["HighestId"] = 7, 
	["LastFinishedQuest"] = 
{
}, 
	["Material"] = true, 
	["DemonProgression"] = 
{
	[1] = 60, 
	[2] = 60
}, 
	["ExpTime"] = 999999999, 
	["BountyUpdates"] = true, 
	["SpawnIsland"] = "TestIsland", 
	["ScreenShake"] = true, 
	["UnlockedMoves"] = 
{
	[1] = "Thunderclap and Flash", 
	[2] = "Heat Lightning", 
	[3] = "Thunderclap and Flash Sixfold", 
	[4] = "Rice Spirit", 
	[5] = "Distance Thunder", 
	[6] = "Thunder Swarm"
}, 
	["Gender"] = "Male", 
	["LastDailyReward"] = 0, 
	["JailTime"] = 0, 
	["New"] = true, 
	["GlobalShadows"] = true, 
	["PickedGender"] = true, 
	["Banned"] = 0, 
	["Inbox"] = 
{
}, 
	["BeliTime"] = 0, 
	["KnockNpc"] = true, 
	["Pvp"] = true
}
local Event = game:GetService("ReplicatedStorage").ScriptCommunication.Set
Event:FireServer(A_1)
